import { Header } from '@/components'
import './globals.css'

export const metadata = {
  title: 'Eleva MKT',
  description: 'Generated by create next app'
}

interface Props {
  children: React.ReactNode
}

function RootLayout({ children }: Props) {
  return (
    <html lang='en'>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
