import { Footer, Header } from '@/components'
import { rubik } from '@/styles'
import '../styles/globals.css'

export const metadata = {
  title: 'Eleva MKT',
  description: 'Generated by create next app'
}

interface Props {
  children: React.ReactNode
}

function RootLayout({ children }: Props) {
  return (
    <html lang='en' className={`${rubik.variable}`}>
      <body className='font-rubik'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}

export default RootLayout
