import { Footer, Header } from '@/components'
import { rubik } from '@/styles'
import '../styles/globals.css'
import Providers from './providers'

export const metadata = {
  title: 'Eleva MKT',
  description: 'Generated by create next app'
}

interface Props {
  children: React.ReactNode
}

function RootLayout({ children }: Props) {
  return (
    <html lang='en' suppressHydrationWarning className={`${rubik.variable}`}>
      <body className='bg-white font-rubik text-black dark:bg-black dark:text-white'>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout
